apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7olm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7olm
    app.kubernetes.io/part-of: tkwch-fix-0075-0066-app
  name: devfile-sample-7olm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7olm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7olm
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0066-tenant/tkwch-fix-0075-0066-app/devfile-sample-7olm@sha256:45736e7b7ae64673aa768236be8466ea2d6619103c2ad902ea4f14029bc6d971
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
